name: chat_box
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  roundcheckbox: ^2.0.4+1
  swipe_cards: ^1.0.0
  salomon_bottom_bar: ^3.3.1
  # fluent_ui:
  fluttertoast: ^8.0.9
  blurrycontainer: ^1.0.2
  http: ^0.13.4
  image_picker: ^0.8.5+3
  dio: ^4.0.6
  get_storage: ^2.0.3
  shared_preferences: ^2.0.15
  flutter_easyloading: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"
  flutter_lints: ^1.0.4

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logos/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logos/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
